umd-lib/drupal-common

- web/themes/custom/umd_libraries/color/color.inc
- web/themes/custom/umd_libraries/umd_libraries.info.yml
Adder Color Picker to Choose Header Color
https://issues.umd.edu/browse/LIBWEB-5135
> LIBWEB-5135 Change header background color in umd_libraries

- web/modules/custom/umd_examples/README.md
Fixed Markdown related to indented bullets, and expanded instructions
regarding using the "UMD Examples" module.
https://issues.umd.edu/browse/LIBITD-1890
> LIBITD-1890. Fixed Markdown and expanded instructions

- web/modules/custom/umd_header_alerts/README.md
- web/modules/custom/umd_header_alerts/config/install/README.md
- web/modules/custom/umd_header_alerts/config/install/core.entity_form_display.node.header_alert.default.yml
- web/modules/custom/umd_header_alerts/config/install/core.entity_view_display.node.header_alert.default.yml
- web/modules/custom/umd_header_alerts/config/install/core.entity_view_display.node.header_alert.teaser.yml
- web/modules/custom/umd_header_alerts/config/install/field.field.node.header_alert.body.yml
- web/modules/custom/umd_header_alerts/config/install/field.field.node.header_alert.field_alert_type.yml
- web/modules/custom/umd_header_alerts/config/install/field.field.node.header_alert.field_icon.yml
- web/modules/custom/umd_header_alerts/config/install/field.storage.node.field_alert_type.yml
- web/modules/custom/umd_header_alerts/config/install/field.storage.node.field_icon.yml
- web/modules/custom/umd_header_alerts/config/install/node.type.header_alert.yml
- web/modules/custom/umd_header_alerts/config/install/pathauto.pattern.alerts.yml
- web/modules/custom/umd_header_alerts/config/install/views.view.sitewide_header_alerts.yml
- web/modules/custom/umd_header_alerts/css/umd-header-alerts.css
- web/modules/custom/umd_header_alerts/umd_header_alerts.info.yml
- web/modules/custom/umd_header_alerts/umd_header_alerts.install
- web/modules/custom/umd_header_alerts/umd_header_alerts.libraries.yml
- web/modules/custom/umd_header_alerts/umd_header_alerts.module
- web/themes/frozen/umd_terp/templates/_includes/global/header.html.twig
- web/themes/frozen/umd_terp/umd_terp.info.yml
https://issues.umd.edu/browse/LIBWEB-5386
> LIBWEB-5386. Header Alerts Feature.

- web/modules/custom/umd_computer_tracking/README.md
- web/modules/custom/umd_computer_tracking/config/install/README.md
- web/modules/custom/umd_computer_tracking/config/install/views.view.workstation_tracking.yml
- web/modules/custom/umd_computer_tracking/css/umd-computer-tracking.css
- web/modules/custom/umd_computer_tracking/umd_computer_tracking.info.yml
- web/modules/custom/umd_computer_tracking/umd_computer_tracking.install
- web/modules/custom/umd_computer_tracking/umd_computer_tracking.libraries.yml
- web/modules/custom/umd_computer_tracking/umd_computer_tracking.module
https://issues.umd.edu/browse/LIBWEB-5364
> LIBWEB-5364. Computer tracking configuration.

- docker-compose.yml
- web/modules/custom/aleph_connector/README.md
- web/modules/custom/aleph_connector/aleph_connector.info.yml
- web/modules/custom/aleph_connector/aleph_connector.links.menu.yml
- web/modules/custom/aleph_connector/aleph_connector.links.task.yml
- web/modules/custom/aleph_connector/aleph_connector.routing.yml
- web/modules/custom/aleph_connector/src/Controller/AlephxController.php
- web/modules/custom/aleph_connector/src/Form/AlephxSettingsForm.php
- web/modules/custom/aleph_connector/src/Helper/AlephxConfigHelper.php
- web/modules/custom/top_textbooks/README.md
- web/modules/custom/top_textbooks/config/install/block.block.facetsblock_3.yml
- web/modules/custom/top_textbooks/config/install/block.block.poweredbydrupal_2.yml
- web/modules/custom/top_textbooks/config/install/facets.facet.program.yml
- web/modules/custom/top_textbooks/config/install/search_api.index.top_textbooks.yml
- web/modules/custom/top_textbooks/config/install/search_api.server.top_textbooks.yml
- web/modules/custom/top_textbooks/config/install/views.view.top_textbooks.yml
- web/modules/custom/top_textbooks/css/top-textbooks.css
- web/modules/custom/top_textbooks/src/Controller/TextbookAvailabilityController.php
- web/modules/custom/top_textbooks/src/Plugin/views/field/TextbookAvailabilityField.php
- web/modules/custom/top_textbooks/templates/textbook-availability-field.html.twig
- web/modules/custom/top_textbooks/top_textbooks.info.yml
- web/modules/custom/top_textbooks/top_textbooks.install
- web/modules/custom/top_textbooks/top_textbooks.libraries.yml
- web/modules/custom/top_textbooks/top_textbooks.module
- web/modules/custom/top_textbooks/top_textbooks.views.inc
https://issues.umd.edu/browse/LIBWEB-5351
> LIBWEB-5351. Implement top-textbooks.

- composer.json
- composer.lock
- web/modules/custom/footer_extend/README.md
- web/modules/custom/footer_extend/config/install/block_content.type.footer_addon.yml
- web/modules/custom/footer_extend/config/install/core.entity_form_display.block_content.footer_addon.default.yml
- web/modules/custom/footer_extend/config/install/core.entity_view_display.block_content.footer_addon.default.yml
- web/modules/custom/footer_extend/config/install/field.field.block_content.footer_addon.field_icon.yml
- web/modules/custom/footer_extend/config/install/field.field.block_content.footer_addon.field_link.yml
- web/modules/custom/footer_extend/config/install/field.storage.block_content.field_icon.yml
- web/modules/custom/footer_extend/config/install/field.storage.block_content.field_link.yml
- web/modules/custom/footer_extend/config/install/system.menu.footer2.yml
- web/modules/custom/footer_extend/css/footer-extend.css
- web/modules/custom/footer_extend/footer_extend.info.yml
- web/modules/custom/footer_extend/footer_extend.install
- web/modules/custom/footer_extend/footer_extend.libraries.yml
- web/modules/custom/footer_extend/footer_extend.module
- web/modules/custom/footer_extend/templates/block--block-content-footer-addon.html.twig
- web/themes/frozen/umd_terp/README-UMDLIB.md
- web/themes/frozen/umd_terp/css/footer.css
- web/themes/frozen/umd_terp/templates/_includes/global/umdlib-footer.html.twig
- web/themes/frozen/umd_terp/templates/block/block--block-content-footer-addon.html.twig
- web/themes/frozen/umd_terp/templates/core/page.html.twig
- web/themes/frozen/umd_terp/theme-settings.php
- web/themes/frozen/umd_terp/umd_terp.info.yml
- web/themes/frozen/umd_terp/umd_terp.libraries.yml
Updated the footer to match the new footer mockup.
- Customized the umd_terp theme footer template and css.
- Added additional footer configuration fields to the umd_terp theme-settings.php
- Created 'footer_extend` module to provide the custom block type and second menu for footer.
- Added new contrib module to composer.json and compose.lock.
https://issues.umd.edu/browse/LIBWEB-5396
> LIBWEB-5396. Footer implementation.

- web/modules/custom/header_search/README.md
- web/modules/custom/header_search/css/header-search.css
- web/modules/custom/header_search/header_search.info.yml
- web/modules/custom/header_search/header_search.install
- web/modules/custom/header_search/header_search.libraries.yml
- web/modules/custom/header_search/header_search.links.menu.yml
- web/modules/custom/header_search/header_search.links.task.yml
- web/modules/custom/header_search/header_search.module
- web/modules/custom/header_search/header_search.routing.yml
- web/modules/custom/header_search/header_search.services.yaml
- web/modules/custom/header_search/src/Form/HeaderSearchForm.php
- web/modules/custom/header_search/src/Form/HeaderSearchSettingsForm.php
- web/modules/custom/header_search/src/Helper/HeaderSearchSettingsHelper.php
- web/modules/custom/header_search/src/Plugin/Block/HeaderSearchBlock.php
- web/modules/custom/header_search/templates/header-search-block.html.twig
https://issues.umd.edu/browse/LIBWEB-5397
> LIBWEB-5397. Header Search implementation.

- web/modules/custom/system_status/README.md
- web/modules/custom/system_status/src/Controller/SystemStatusController.php
- web/modules/custom/system_status/src/Form/SystemStatusSettingsForm.php
- web/modules/custom/system_status/system_status.info.yml
- web/modules/custom/system_status/system_status.install
- web/modules/custom/system_status/system_status.links.menu.yml
- web/modules/custom/system_status/system_status.links.task.yml
- web/modules/custom/system_status/system_status.module
- web/modules/custom/system_status/system_status.routing.yml
https://issues.umd.edu/browse/LIBWEB-5398
> LIBWEB-5398. System status module implementation.

- web/modules/custom/hero_search/README.md
- web/modules/custom/hero_search/css/hero-search.css
- web/modules/custom/hero_search/hero_search.info.yml
- web/modules/custom/hero_search/hero_search.install
- web/modules/custom/hero_search/hero_search.libraries.yml
- web/modules/custom/hero_search/hero_search.links.menu.yml
- web/modules/custom/hero_search/hero_search.links.task.yml
- web/modules/custom/hero_search/hero_search.module
- web/modules/custom/hero_search/hero_search.routing.yml
- web/modules/custom/hero_search/hero_search.services.yml
- web/modules/custom/hero_search/src/Form/HeroSearchForm.php
- web/modules/custom/hero_search/src/Form/HeroSearchSettingsForm.php
- web/modules/custom/hero_search/src/Helper/HeroSearchSettingsHelper.php
- web/modules/custom/hero_search/src/Plugin/Block/HeroSearchBlock.php
- web/modules/custom/hero_search/templates/hero-search-block.html.twig
- web/modules/custom/hero_search/templates/hero-search-form.html.twig
- web/themes/frozen/umd_terp/css/hero-block.css
- web/themes/frozen/umd_terp/inc/preprocess.inc
- web/themes/frozen/umd_terp/templates/node/umd-terp-homepage/node--umd-terp-homepage.html.twig
- web/themes/frozen/umd_terp/umd_terp.info.yml
- web/themes/frozen/umd_terp/umd_terp.libraries.yml
https://issues.umd.edu/browse/LIBWEB-5401
> LIBWEB-5410. Implement Hero Search module.

- web/themes/frozen/umd_terp/css/hero-block.css
- web/themes/frozen/umd_terp/inc/preprocess.inc
- web/themes/frozen/umd_terp/templates/node/umd-terp-homepage/node--umd-terp-homepage.html.twig
- web/themes/frozen/umd_terp/umd_terp.info.yml
- web/themes/frozen/umd_terp/umd_terp.libraries.yml
https://issues.umd.edu/browse/LIBWEB-5399
> LIBWEB-5399. Hero Block module implementation.

- web/modules/custom/aleph_connector/aleph_connector.info.yml
- web/modules/custom/aleph_connector/aleph_connector.links.menu.yml
- web/modules/custom/aleph_connector/aleph_connector.links.task.yml
- web/modules/custom/aleph_connector/aleph_connector.routing.yml
- web/modules/custom/libraries_configuration/libraries_configuration.info.yml
- web/modules/custom/libraries_configuration/libraries_configuration.install
- web/modules/custom/libraries_configuration/libraries_configuration.links.menu.yml
- web/modules/custom/libraries_configuration/libraries_configuration.links.task.yml
- web/modules/custom/libraries_configuration/libraries_configuration.module
- web/modules/custom/libraries_configuration/libraries_configuration.routing.yml
- web/modules/custom/libraries_configuration/src/Controller/LibrariesConfigurationController.php
- web/modules/custom/system_status/system_status.info.yml
- web/modules/custom/system_status/system_status.links.menu.yml
- web/modules/custom/system_status/system_status.links.task.yml
https://issues.umd.edu/browse/LIBWEB-5408
> LIBWEB-5408. Libraries config menu module.

- web/modules/custom/aleph_connector/modules/equipment_tracking/config/install/views.view.equipment_tracking.yml
- web/modules/custom/aleph_connector/modules/equipment_tracking/css/equipment-tracking.css
- web/modules/custom/aleph_connector/modules/equipment_tracking/templates/aleph-equipment-available.html.twig
- Made layout and style changes.
> LIBWEB-5381. Theme Equipment Availability

- web/modules/custom/lib_cal/css/lib-cal.css
- web/modules/custom/lib_cal/lib_cal.info.yml
- web/modules/custom/lib_cal/lib_cal.install
- web/modules/custom/lib_cal/lib_cal.libraries.yml
- web/modules/custom/lib_cal/lib_cal.links.task.yml
- web/modules/custom/lib_cal/lib_cal.module
- web/modules/custom/lib_cal/lib_cal.permissions.yml
- web/modules/custom/lib_cal/lib_cal.routing.yml
- web/modules/custom/lib_cal/src/Controller/LibCalController.php
- web/modules/custom/lib_cal/src/Controller/test.php
- web/modules/custom/lib_cal/src/Form/LibCalSettingsForm.php
- web/modules/custom/lib_cal/src/Helper/LibCalApiHelper.php
- web/modules/custom/lib_cal/src/Helper/LibCalSettingsHelper.php
- web/modules/custom/lib_cal/src/Plugin/Block/LibCalBlock.php
- web/modules/custom/lib_cal/templates/lib-cal-block.html.twig
https://issues.umd.edu/browse/LIBWEB-5403
> LIBWEB-5403. LibCal Implementation.

- web/modules/custom/aleph_connector/aleph_connector.module
- web/modules/custom/aleph_connector/src/Controller/AlephController.php
https://issues.umd.edu/browse/LIBWEB-5413
> LIBWEB-5413. Cache Aleph Connector data.

- web/modules/custom/library_services/config/install/core.entity_form_display.node.services_resources.default.yml
- web/modules/custom/library_services/config/install/field.field.node.services_resources.field_description.yml
- web/modules/custom/library_services/config/install/field.field.node.services_resources.field_icon.yml
- web/modules/custom/library_services/config/install/field.field.node.services_resources.field_link.yml
- web/modules/custom/library_services/config/install/field.storage.node.field_description.yml
- web/modules/custom/library_services/config/install/field.storage.node.field_icon.yml
- web/modules/custom/library_services/config/install/field.storage.node.field_link.yml
- web/modules/custom/library_services/config/install/node.type.services_resources.yml
- web/modules/custom/library_services/config/install/pathauto.pattern.services_resources.yml
- web/modules/custom/library_services/config/install/views.view.services_resources_block.yml
- web/modules/custom/library_services/css/library-services.css
- web/modules/custom/library_services/library_services.info.yml
- web/modules/custom/library_services/library_services.install
- web/modules/custom/library_services/library_services.libraries.yml
- web/modules/custom/library_services/library_services.module
- Adds a "Services & Resources" content type
- Adds a "Services & Resources Block" view that displays (up to) the 4 most recently published Services & Resources nodes
- Styles to display the Services & Resources following the guidance of the wireframes
- FontAwesome icons are used for the "Icon" field
https://issues.umd.edu/browse/LIBWEB-5410
> LIBWEB-5410. Services & Resources module.

- web/themes/frozen/umd_terp/templates/_includes/global/umdlib-footer.html.twig
- web/themes/frozen/umd_terp/theme-settings.php
https://issues.umd.edu/browse/LIBWEB-5418
> LIBWEB-5418. Added ASK US Widget.

- web/modules/custom/umd_header_alerts/css/umd-header-alerts.css
- web/themes/frozen/umd_terp/templates/_includes/global/header.html.twig
- web/themes/frozen/umd_terp/templates/core/page--node--umd-terp-homepage.html.twig
- web/themes/frozen/umd_terp/templates/core/page.html.twig
https://issues.umd.edu/browse/LIBWEB-5415
> LIBWEB-5415. Move header alert location.

- web/modules/custom/library_services/css/library-services.css
https://issues.umd.edu/browse/LIBWEB-5427
> LIBWEB-5427. Theme Services & Resources.

- web/themes/frozen/umd_terp/templates/core/page--node--umd-terp-article.html.twig
- web/themes/frozen/umd_terp/templates/core/page--node--umd-terp-event.html.twig
- web/themes/frozen/umd_terp/templates/core/page--user--login.html.twig
- web/themes/frozen/umd_terp/templates/node/umd-terp-basic-page/node--umd-terp-basic-page.html.twig
- web/themes/frozen/umd_terp/templates/node/umd-terp-person/node--umd-terp-person.html.twig
- web/themes/frozen/umd_terp/theme-settings.php
https://issues.umd.edu/browse/LIBWEB-5421
> LIBWEB-5421. Option to disable Page Title.

- web/modules/custom/lib_cal/css/lib-cal.css
- web/modules/custom/lib_cal/templates/lib-cal-block.html.twig
https://issues.umd.edu/browse/LIBWEB-5419
> LIBWEB-5419. LibCal Theming Work.

- web/modules/custom/aleph_connector/aleph_connector.routing.yml
- web/modules/custom/header_search/header_search.info.yml
- web/modules/custom/header_search/header_search.routing.yml
- web/modules/custom/hero_search/hero_search.info.yml
- web/modules/custom/hero_search/hero_search.routing.yml
- web/modules/custom/libraries_configuration/libraries_configuration.info.yml
- web/modules/custom/libraries_configuration/libraries_configuration.permissions.yml
https://issues.umd.edu/browse/LIBWEB-5435
> LIBWEB-5435. Add custom permission for custom modules.

- web/themes/frozen/umd_terp/css/hero-block.css
- web/themes/frozen/umd_terp/templates/node/umd-terp-homepage/node--umd-terp-homepage.html.twig
https://issues.umd.edu/browse/LIBWEB-5439
> LIBWEB-5439. Add Hidden H1 in UMD Terp Homepage.

- web/modules/custom/umd_header_alerts/config/install/views.view.sitewide_header_alerts.yml
- web/modules/custom/umd_header_alerts/css/umd-header-alerts.css
- web/themes/frozen/umd_terp/templates/core/page--node--umd-terp-homepage.html.twig
https://issues.umd.edu/browse/LIBWEB-5426
> LIBWEB-5426. Theme Header Alerts.

- web/modules/custom/top_textbooks/config/install/views.view.top_textbooks.yml
- web/modules/custom/top_textbooks/css/top-textbooks.css
https://issues.umd.edu/browse/LIBWEB-5451
> LIBWEB-5451. Add comment field to top textbooks.

- web/themes/frozen/umd_terp/inc/preprocess.inc
https://issues.umd.edu/browse/LIBWEB-5434
> LIBWEB-5434. Suppress page title on home page.

- web/modules/custom/umd_libraries_hours/config/install/views.view.hours_today.yml
- web/modules/custom/umd_libraries_hours/umd_libraries_hours.views_execution.inc
https://issues.umd.edu/browse/LIBWEB-5433
> LIBWEB-5433. Hardcode the hours today filter condition.

- web/modules/custom/lib_cal/src/Plugin/Block/LibCalBlock.php
https://issues.umd.edu/browse/LIBWEB-5458
> LIBWEB-5458. Configure LibCal block cache.

- web/modules/custom/header_search/header_search.info.yml
- web/modules/custom/header_search/header_search.links.menu.yml
- web/modules/custom/header_search/header_search.links.task.yml
- web/modules/custom/hero_search/hero_search.info.yml
- web/modules/custom/hero_search/hero_search.links.task.yml
- web/modules/custom/libraries_search/libraries_search.info.yml
- web/modules/custom/libraries_search/libraries_search.install
- web/modules/custom/libraries_search/libraries_search.links.menu.yml
- web/modules/custom/libraries_search/libraries_search.links.task.yml
- web/modules/custom/libraries_search/libraries_search.module
- web/modules/custom/libraries_search/libraries_search.routing.yml
- web/modules/custom/libraries_search/src/Controller/LibrariesSearchController.php
https://issues.umd.edu/browse/LIBWEB-5459
> LIBWEB-5459.Add Libraries Search configuration menu.

- web/modules/custom/newsroom/config/install/views.view.news_event_block.yml
- web/modules/custom/newsroom/css/newsroom.css
- web/modules/custom/newsroom/newsroom.info.yml
- web/modules/custom/newsroom/newsroom.install
- web/modules/custom/newsroom/newsroom.libraries.yml
- web/modules/custom/newsroom/newsroom.module
Pulls the 10 most recent articles, finds the first one with an image and puts it at the top of the list, then keeps the next 5. Displays via a grid with the featured article in the left third, the 5 other articles in the middle, and the events block in the right third.
This includes some basic styling for the layout and some of the text properties.
https://issues.umd.edu/browse/LIBWEB-5462
> LIBWEB-5462. Implemented News & Events View.

- composer.json
- composer.lock
- web/modules/custom/newsroom/css/newsroom.css
- web/modules/custom/ut_block/README.md
- web/modules/custom/ut_block/config/install/core.entity_form_display.paragraph.ut_block_2_columns.default.yml
- web/modules/custom/ut_block/config/install/core.entity_view_display.paragraph.ut_block_2_columns.default.yml
- web/modules/custom/ut_block/config/install/field.field.paragraph.ut_block_2_columns.field_ut_block_2_columns_column1.yml
- web/modules/custom/ut_block/config/install/field.field.paragraph.ut_block_2_columns.field_ut_block_2_columns_column2.yml
- web/modules/custom/ut_block/config/install/field.storage.paragraph.field_ut_block_2_columns_column1.yml
- web/modules/custom/ut_block/config/install/field.storage.paragraph.field_ut_block_2_columns_column2.yml
- web/modules/custom/ut_block/config/install/paragraphs.paragraphs_type.ut_block_2_columns.yml
- web/modules/custom/ut_block/css/ut-block.css
- web/modules/custom/ut_block/templates/paragraph--ut-block-2-columns.html.twig
- web/modules/custom/ut_block/ut_block.info.yml
- web/modules/custom/ut_block/ut_block.install
- web/modules/custom/ut_block/ut_block.libraries.yml
- web/modules/custom/ut_block/ut_block.module
Used "block_field" module (https://www.drupal.org/project/block_field) 
to enable custom blocks to be added to paragraphs.
Added a custom "ut_block" module, patterned after "ut_text" to provide
a two-column layout for custom blocks.
Made updates to "newsrooms" CSS to provide a better display when
displayed in columns, and stand-alone.
https://issues.umd.edu/browse/LIBWEB-5429
> LIBWEB-5429. Create View of Views of Newsfeed and LibCal

- composer.json
- composer.lock
- web/modules/custom/newsroom/config/install/views.view.news_navigation.yml
- web/modules/custom/newsroom/newsroom.info.yml
- web/modules/custom/newsroom/newsroom.views_execution.inc
https://issues.umd.edu/browse/LIBWEB-5481
> LIBWEB-5481. Add Previous/Next news navigation.

- web/themes/frozen/umd_terp/umd_terp.info.yml
https://issues.umd.edu/browse/LIBWEB-5470
> LIBWEB-5470. Updated core version requirement.

- web/themes/frozen/umd_terp/inc/preprocess.inc
https://issues.umd.edu/browse/LIBWEB-5469
> LIBWEB-5469. Replace deprecated methods for D9 readiness.

- web/modules/custom/newsroom/newsroom.routing.yml
- web/modules/custom/newsroom/src/Plugin/Menu/NewsMenuLink.php
https://issues.umd.edu/browse/LIBWEB-5516
> LIBWEB-5516. Allow display of dynamic menu item in menu admin page.

- web/modules/custom/newsroom/config/install/pathauto.pattern.news_categories.yml
- web/modules/frozen/umd_terp_base/modules/umd_terp_content_types/umd_terp_content_types.module
https://issues.umd.edu/browse/LIBWEB-5509
> LIBWEB-5509. Update taxonomy term url.

- web/modules/custom/ask_us/README.md
- web/modules/custom/ask_us/ask_us.info.yml
- web/modules/custom/ask_us/ask_us.install
- web/modules/custom/ask_us/ask_us.libraries.yml
- web/modules/custom/ask_us/ask_us.module
- web/modules/custom/ask_us/config/install/block_content.type.ask_us.yml
- web/modules/custom/ask_us/config/install/core.entity_form_display.block_content.ask_us.default.yml
- web/modules/custom/ask_us/config/install/core.entity_view_display.block_content.ask_us.default.yml
- web/modules/custom/ask_us/config/install/field.field.block_content.ask_us.field_link1.yml
- web/modules/custom/ask_us/config/install/field.field.block_content.ask_us.field_link2.yml
- web/modules/custom/ask_us/config/install/field.field.block_content.ask_us.field_search.yml
- web/modules/custom/ask_us/config/install/field.field.block_content.ask_us.field_social_link1.yml
- web/modules/custom/ask_us/config/install/field.field.block_content.ask_us.field_social_link1_icon.yml
- web/modules/custom/ask_us/config/install/field.field.block_content.ask_us.field_social_link2.yml
- web/modules/custom/ask_us/config/install/field.field.block_content.ask_us.field_social_link2_icon.yml
- web/modules/custom/ask_us/config/install/field.field.block_content.ask_us.field_social_link3.yml
- web/modules/custom/ask_us/config/install/field.field.block_content.ask_us.field_social_link3_icon.yml
- web/modules/custom/ask_us/config/install/field.storage.block_content.field_link1.yml
- web/modules/custom/ask_us/config/install/field.storage.block_content.field_link2.yml
- web/modules/custom/ask_us/config/install/field.storage.block_content.field_search.yml
- web/modules/custom/ask_us/config/install/field.storage.block_content.field_social_link1.yml
- web/modules/custom/ask_us/config/install/field.storage.block_content.field_social_link1_icon.yml
- web/modules/custom/ask_us/config/install/field.storage.block_content.field_social_link2.yml
- web/modules/custom/ask_us/config/install/field.storage.block_content.field_social_link2_icon.yml
- web/modules/custom/ask_us/config/install/field.storage.block_content.field_social_link3.yml
- web/modules/custom/ask_us/config/install/field.storage.block_content.field_social_link3_icon.yml
- web/modules/custom/ask_us/config/install/fixed_block_content.fixed_block_content.ask_a_librarian.yml
- web/modules/custom/ask_us/css/ask-us.css
- web/modules/custom/ask_us/templates/block--fixed-block-content--ask-a-librarian.html.twig
https://issues.umd.edu/browse/LIBWEB-5506
> LIBWEB-5506. Ask Us Utility Nav Block.

- web/modules/custom/utility_nav/config/install/block.block.infofor.yml
- web/modules/custom/utility_nav/config/install/system.menu.info-for.yml
- web/modules/custom/utility_nav/css/utility-nav.css
- web/modules/custom/utility_nav/templates/block--system-menu-block--info-for.html.twig
- web/modules/custom/utility_nav/utility_nav.module
https://issues.umd.edu/browse/LIBWEB-5508
> LIBWEB-5508. Info For Utility Nav Block.

- web/modules/custom/aleph_connector/src/Controller/AlephxController.php
- web/modules/custom/top_textbooks/src/Controller/TextbookAvailabilityController.php
- web/modules/custom/top_textbooks/src/Plugin/views/field/TextbookAvailabilityField.php
https://issues.umd.edu/browse/LIBWEB-5517
> LIBWEB-5517. Improve Textbook Availability logging.

- web/modules/custom/newsroom/newsroom.install
- web/modules/custom/umd_staff_directory/umd_terp_person_extensions/umd_terp_person_extensions.install
https://issues.umd.edu/browse/LIBWEB-5522
> LIBWEB-5522. Add/Remove dynamic menu link mapping conditionally.

- web/modules/custom/hero_search/css/hero-search.css
- web/modules/custom/library_services/css/library-services.css
- web/modules/custom/umd_header_alerts/css/umd-header-alerts.css
- web/themes/frozen/umd_terp/css/footer.css
- web/themes/frozen/umd_terp/css/utility-nav.css
- web/themes/frozen/umd_terp/templates/core/page.html.twig
- Fixed Services mobile display
- Fixed Header alert mobile display, also adjusted the background color
https://issues.umd.edu/browse/LIBWEB-5492
> LIBWEB-5492 - Mobile display: Services area on homepage

- web/modules/custom/lib_cal/css/lib-cal.css
- web/modules/custom/library_services/css/library-services.css
- web/modules/custom/newsroom/css/news_page.css
- web/modules/custom/newsroom/css/newsroom.css
- web/modules/custom/ut_block/templates/paragraph--ut-block-2-columns.html.twig
- web/themes/frozen/umd_terp/css/article.css
- web/themes/frozen/umd_terp/templates/core/page.html.twig
- Modified mobil displays for news section on both homepage and /about/news
> LIBWEB-5500. Theme Newsroom articles and feed on homepage and Newsroom

- web/modules/custom/ask_us/css/ask-us.css
- web/modules/custom/ask_us/templates/ask-a-librarian-util-mobile.html.twig
- web/modules/custom/ask_us/templates/ask-a-librarian-util.html.twig
- web/themes/frozen/umd_terp/css/footer.css
- web/themes/frozen/umd_terp/js/chatwidget.js
- web/themes/frozen/umd_terp/templates/_includes/global/umdlib-footer.html.twig
- web/themes/frozen/umd_terp/umd_terp.libraries.yml
- update chat with us button in utility nav with new button design
- update chat with us main button with new chatbox design
- add javascript to monitor the chat widget status and update chat with us button style accordingly.
https://umd-dit.atlassian.net/browse/LIBWEB-5975
> LIBWEB-5975. WWW - new chat widget design implementation

- web/themes/frozen/umd_terp/templates/core/page--node--umd-terp-homepage.html.twig
- web/themes/frozen/umd_terp/templates/core/page.html.twig
- web/themes/frozen/umd_terp/umd_terp.info.yml
- create a new region "Local Utility"
- add the region to page.html.twig & umd-terp-homepage.html.twig
https://umd-dit.atlassian.net/browse/LIBWEB-5976
> LIBWEB-5976. Create new region "Local Utility" for language switcher

- web/modules/custom/ask_us/templates/ask-a-librarian-util-mobile.html.twig
- web/modules/custom/ask_us/templates/ask-a-librarian-util.html.twig
- web/themes/frozen/umd_terp/css/footer.css
- web/themes/frozen/umd_terp/js/chatwidget.js
- web/themes/frozen/umd_terp/templates/_includes/global/umdlib-footer.html.twig
- implement a function to update the chat service URL, adding referer information.
- add a function to the "Chat with Us!" button in the navigation bar to include referer information.
- update the Twig files, specifically "umdlib-footer.html.twig" and "ask-a-librarian-utl.html.twig," to support the changes and improve accessibility.
- refine the style of the chat widget, addressing minor UI issues.
https://umd-dit.atlassian.net/browse/LIBWEB-6004
> LIBWEB-6004. WWW - provide referrer info to springshare via chat widget

- web/themes/frozen/umd_terp/css/feedback-popup.css
- web/themes/frozen/umd_terp/js/feedback-popup.js
- web/themes/frozen/umd_terp/templates/core/page--node--umd-terp-homepage.html.twig
- web/themes/frozen/umd_terp/umd_terp.info.yml
- web/themes/frozen/umd_terp/umd_terp.libraries.yml
- Update Twig and YAML files for the new region "bento utility footer" on the Bento search result page
- Add custom JavaScript and CSS for the feedback popup
https://umd-dit.atlassian.net/browse/LIBWEB-6133
> LIBWEB-6133. As a UX designer, I want to collect user feedback on the search all results, so that we can improve the search experience

- web/themes/frozen/umd_terp/css/hero-block.css
- Update CSS to fix embedded heading
- Remove duplicated CSS
https://umd-dit.atlassian.net/browse/LIBWEB-6147
> LIBWEB-6147. H1 appears on bento search results page

- web/modules/custom/mirador_viewer/css/mirador-details.css
- Update CSS to remove CSS nesting for the item page in the digital collections.
https://umd-dit.atlassian.net/browse/LIBWEB-6148
> LIBWEB-6148. WWW - css failed to load on older operating systems

- web/themes/frozen/umd_terp/css/hero-block.css
- web/themes/frozen/umd_terp/templates/node/umd-terp-homepage/node--umd-terp-homepage.html.twig
- update css selector to target element only on the homepage
https://umd-dit.atlassian.net/browse/LIBWEB-6203
> LIBWEB-6203. Hero background issue if no hero block

- web/modules/custom/hero_search/css/hero-search.css
- web/modules/custom/hero_search/hero_search.module
- web/modules/custom/hero_search/js/form_util.js
- web/modules/custom/hero_search/src/Form/HeroSearchForm.php
- web/modules/custom/hero_search/src/Helper/HeroSearchSettingsHelper.php
- web/modules/custom/hero_search/src/Plugin/Block/HeroSearchBlock.php
- web/modules/custom/hero_search/templates/hero-search-block.html.twig
- add the tab design for the search box on the homepage.
https://umd-dit.atlassian.net/browse/LIBWEB-6196
> LIBWEB-6196. Build tabbed homepage search interface

- web/modules/custom/hero_search/css/hero-search.css
- web/modules/custom/hero_search/templates/hero-search-block.html.twig
- remove UMD Discover link section
- update styling
https://umd-dit.atlassian.net/browse/LIBWEB-6266
> LIBWEB-6266. WWW - homepage search box link layout update
